[project]
name = "diacritical-web"
version = "0.1.0"
description = "A web frontend for running diacritical"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.3",
    "python-dotenv>=1.1.0",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
]
