# Generated by Django 5.2.3 on 2025-06-21 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("terms", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="run",
            old_name="run_time",
            new_name="start_time",
        ),
    ]
