# Generated by Django 5.2.3 on 2025-06-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terms", "0002_rename_run_time_run_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="url",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
