# Generated by Django 5.2.3 on 2025-06-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terms", "0003_finding_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="page_name",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
