# Generated by Django 5.2.3 on 2025-06-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terms", "0004_finding_page_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="secret",
            field=models.CharField(default=2, max_length=32),
            preserve_default=False,
        ),
    ]
