# Generated by Django 5.2.3 on 2025-06-22 08:54

import django.utils.timezone
from django.db import migrations, models
from terms.models import random_secret


class Migration(migrations.Migration):

    replaces = [
        ("terms", "0005_run_secret"),
        ("terms", "0006_alter_run_secret_alter_run_start_time"),
        ("terms", "0007_alter_run_secret_alter_run_start_time"),
        ("terms", "0008_alter_run_secret"),
    ]

    dependencies = [
        ("terms", "0004_finding_page_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="run",
            name="start_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="run",
            name="secret",
            field=models.CharField(default=random_secret, max_length=32),
        ),
    ]
