# Generated by Django 5.2.3 on 2025-06-22 01:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terms", "0005_run_secret"),
    ]

    operations = [
        migrations.AlterField(
            model_name="run",
            name="secret",
            field=models.CharField(
                default="SVxVdgvCVrMZNBAZXdLEAE9VYnATECn9", max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="run",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 6, 22, 1, 7, 31, 374636, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
